Support node versions >=14
In b124989b5d32a5832393b4a222e9579c27e61b44 the @types/node
dependency was changed from "*" to ">=4.2.0 < 13"
in order to fix the following error:

    ../jest-haste-map/build/index.d.ts:125:32 - error TS2507: Type 'typeof EventEmitter' is not a constructor function type.

Node 12 however has already reached it's end-of-life on 2022-04-30[1],
so this commit instead simply bumps the jest dependency versions.

[1]: https://github.com/nodejs/release#end-of-life-releases